# Generated by Django 5.0.6 on 2024-07-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Candidate",
        ),
    ]
