# Generated by Django 5.0.6 on 2024-07-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_delete_candidate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobInterview",
        ),
    ]
