# Generated by Django 5.0.6 on 2024-07-30 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_delete_jobinterview"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_id", models.CharField(max_length=45)),
                ("interview_method_id", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("reschedule_start_date", models.DateTimeField()),
                ("reschedule_end_date", models.DateTimeField()),
                ("reschedule_by", models.CharField(max_length=45)),
                ("status", models.CharField(max_length=45)),
                ("feedback", models.TextField()),
                ("meeting_url", models.TextField()),
                ("event_id", models.TextField()),
                ("rating", models.TextField()),
                ("expired_at", models.CharField(max_length=45)),
                ("cancel_reason", models.TextField()),
                (
                    "jobpost_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment.jobpost",
                    ),
                ),
            ],
        ),
    ]
