# Generated by Django 5.0.6 on 2024-07-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0005_alter_jobinterview_reschedule_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinterview",
            name="cancel_reason",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
