# Generated by Django 5.0.6 on 2024-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_timezone_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('timezone', models.CharField(blank=True, choices=[('UTC', 'Coordinated Universal Time'), ('US/Eastern', 'Eastern Time (US & Canada)'), ('US/Central', 'Central Time (US & Canada)')], max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Timezone',
        ),
    ]
