# Generated by Django 5.0.6 on 2024-07-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("job_type_id", models.IntegerField()),
                ("description", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                ("salary_type_id", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("experience_required", models.IntegerField()),
                ("education_required", models.TextField()),
                ("skills", models.TextField()),
                ("gender", models.CharField(max_length=45)),
                ("status", models.CharField(max_length=45)),
                ("closed_reason", models.TextField()),
                ("expired_date", models.DateTimeField()),
                ("shift_type_id", models.IntegerField()),
                ("shift_start", models.DateTimeField()),
                ("shift_end", models.DateTimeField()),
                ("shift_hours", models.IntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.organization",
                    ),
                ),
            ],
        ),
    ]
