# Generated by Django 5.0.6 on 2024-07-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_jobpost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobPost",
        ),
    ]
