# Generated by Django 5.0.6 on 2024-07-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_delete_jobpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="organization",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
