# Generated by Django 5.0.6 on 2024-07-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_remove_location_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45, unique=True)),
                ("phone", models.CharField(max_length=45)),
                ("country_id", models.IntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, max_length=45, null=True)),
                ("logo", models.TextField(blank=True, null=True)),
                ("industry_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="employee.organization",
                    ),
                ),
            ],
        ),
    ]
