# Generated by Django 5.0.6 on 2024-05-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_language_skill_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Industry', 'Industry'), ('Country', 'Country'), ('State', 'State'), ('City', 'City'), ('Designation', 'Designation'), ('Department', 'Department'), ('Source', 'Source'), ('DegreeType', 'Degree Type'), ('EmployeeType', 'Employee Type'), ('JobType', 'Job Type'), ('Relation', 'Relation'), ('Skill', 'Skill'), ('Language', 'Language')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
    ]
