# Generated by Django 5.0.6 on 2024-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_userprofile_alter_dependent_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='category',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Country', 'Country'), ('State', 'State'), ('City', 'City'), ('Designation', 'Designation'), ('Department', 'Department'), ('Source', 'Source'), ('DegreeType', 'Degree Type'), ('EmployeeType', 'Employee Type'), ('JobType', 'Job Type'), ('Relation', 'Relation'), ('Skill', 'Skill'), ('Language', 'Language')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
