# Generated by Django 5.0.6 on 2024-05-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_relation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='iban',
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='employee.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='employee.userprofile')),
            ],
        ),
    ]
