# Generated by Django 5.0.6 on 2024-05-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_remove_userprofile_account_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
