# Generated by Django 5.0.6 on 2024-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_rename_personal_email_userprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolePermission',
            new_name='Role_has_Permission',
        ),
    ]
