# Generated by Django 5.0.6 on 2024-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0026_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_currency",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(default="", max_length=34),
        ),
    ]
