# Generated by Django 5.0.6 on 2024-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0028_alter_userprofile_date_of_joining_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="employee_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="source_of_hiring",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
