# Generated by Django 5.0.6 on 2024-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0030_alter_bankaccount_account_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencycontact",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="iban",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.DeleteModel(
            name="BankAccount",
        ),
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
    ]
