# Generated by Django 5.0.6 on 2024-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0031_remove_emergencycontact_user_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="relation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
