# Generated by Django 5.0.6 on 2024-06-06 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0032_userprofile_name_userprofile_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(max_length=128)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=45)),
                ("designation_id", models.IntegerField()),
                ("department_id", models.IntegerField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("id_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("location_id", models.CharField(max_length=45)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                (
                    "social_insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "source_of_hiring",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                (
                    "employee_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("exit_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Resigned", "Resigned"),
                            ("Terminated", "Terminated"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "reporting_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="employee.role",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
