# Generated by Django 5.0.6 on 2024-06-06 07:38

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0033_employee_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="about",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id_number",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="employee",
            name="location_id",
            field=models.CharField(default="", max_length=45),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(default="unmarried", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(default="", max_length=45),
        ),
        migrations.AlterField(
            model_name="employee",
            name="postal_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.fields.SmallIntegerField,
                related_name="users",
                to="employee.role",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="social_insurance_number",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="source_of_hiring",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
    ]
