# Generated by Django 5.0.6 on 2024-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0034_alter_employee_about_alter_employee_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
    ]
