# Generated by Django 5.0.6 on 2024-06-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0035_employee_is_active_employee_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="designation_id",
            field=models.IntegerField(null=True),
        ),
    ]
