# Generated by Django 5.0.6 on 2024-06-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0036_alter_employee_designation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department_id",
            field=models.IntegerField(null=True),
        ),
    ]
