# Generated by Django 5.0.6 on 2024-06-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0037_alter_employee_department_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
