# Generated by Django 5.0.6 on 2024-06-07 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0038_employee_last_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=45)),
                ("iban", models.CharField(max_length=45)),
                ("account_number", models.CharField(max_length=45)),
                ("currency", models.CharField(max_length=45)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
                ("relation", models.CharField(max_length=45)),
                ("address", models.TextField()),
                ("country_id", models.IntegerField()),
                ("state_id", models.IntegerField()),
                ("city_id", models.IntegerField()),
                ("postal_code", models.CharField(max_length=45)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
