# Generated by Django 5.0.6 on 2024-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0039_bankaccount_emergencycontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="country_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
