# Generated by Django 5.0.6 on 2024-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0040_alter_emergencycontact_country_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="city_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="state_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
