# Generated by Django 5.0.6 on 2024-06-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0041_alter_emergencycontact_city_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="user",
            new_name="employee",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="user",
            new_name="employee",
        ),
    ]
