# Generated by Django 5.0.6 on 2024-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0042_rename_user_education_employee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dependent",
            old_name="user",
            new_name="employee_id",
        ),
    ]
