# Generated by Django 5.0.6 on 2024-06-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0043_rename_user_dependent_employee_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lookup",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="skill",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
