# Generated by Django 5.0.6 on 2024-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0044_country_degreetype_department_designation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="state",
        ),
        migrations.RemoveField(
            model_name="state",
            name="country",
        ),
        migrations.DeleteModel(
            name="DegreeType",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Designation",
        ),
        migrations.DeleteModel(
            name="EmployeeType",
        ),
        migrations.DeleteModel(
            name="Industry",
        ),
        migrations.DeleteModel(
            name="JobType",
        ),
        migrations.DeleteModel(
            name="Lang",
        ),
        migrations.DeleteModel(
            name="Relation",
        ),
        migrations.DeleteModel(
            name="Skills",
        ),
        migrations.DeleteModel(
            name="Source",
        ),
        migrations.AddField(
            model_name="lookup",
            name="capital",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lookup",
            name="category",
            field=models.CharField(
                choices=[
                    ("Industry", "Industry"),
                    ("Country", "Country"),
                    ("State", "State"),
                    ("City", "City"),
                    ("Designation", "Designation"),
                    ("Department", "Department"),
                    ("Source", "Source"),
                    ("DegreeType", "Degree Type"),
                    ("EmployeeType", "Employee Type"),
                    ("JobType", "Job Type"),
                    ("Relation", "Relation"),
                    ("Skill", "Skill"),
                    ("Language", "Language"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lookup",
            name="currency",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lookup",
            name="iso2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lookup",
            name="iso3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lookup",
            name="phone_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lookup",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lookup",
            name="status",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
