# Generated by Django 5.0.6 on 2024-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0045_remove_city_state_remove_state_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookup",
            name="status",
            field=models.CharField(default="", max_length=50),
        ),
    ]
