# Generated by Django 5.0.6 on 2024-06-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0046_alter_lookup_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookup",
            name="status",
        ),
    ]
