# Generated by Django 5.0.6 on 2024-06-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0047_remove_lookup_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookup",
            name="status",
            field=models.CharField(default="True", max_length=50),
        ),
    ]
