# Generated by Django 5.0.6 on 2024-06-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0048_lookup_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lookup",
        ),
    ]
