# Generated by Django 5.0.6 on 2024-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0002_remove_country_status_country_capital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="state_code",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="state",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
