# Generated by Django 5.0.6 on 2024-06-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0003_state_state_code_alter_state_id_alter_state_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="state_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
