# Generated by Django 5.0.6 on 2024-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0004_alter_state_state_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
