# Generated by Django 5.0.6 on 2024-06-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("password", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
                ("father_name", models.CharField(max_length=45)),
                ("source_id", models.IntegerField()),
                ("status", models.CharField(max_length=45)),
                ("birth_date", models.DateField()),
                ("id_number", models.CharField(max_length=45)),
                ("marital_status", models.CharField(max_length=45)),
                ("gender", models.CharField(max_length=45)),
                ("picture", models.CharField(max_length=45)),
                ("cover_photo", models.CharField(max_length=45)),
                ("about", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_profile_id", models.IntegerField()),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile_skills",
                        to="job_seekers.skill",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="job_seekers.skillcategory",
            ),
        ),
    ]
