# Generated by Django 5.0.6 on 2024-06-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("education_type_id", models.CharField(max_length=45)),
                ("major_subjects", models.CharField(max_length=45)),
                ("score", models.CharField(max_length=45)),
                ("completion_date", models.DateField()),
                ("institute_name", models.CharField(max_length=45)),
                ("certificate_photo", models.CharField(max_length=45)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("job_type_id", models.CharField(max_length=45)),
                ("company_name", models.CharField(max_length=45)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=45)),
                ("experience_letter_photo", models.CharField(max_length=45)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
    ]
