# Generated by Django 5.0.6 on 2024-06-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_education_jobprofileexperience"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title_id", models.CharField(max_length=45)),
                ("hourly_rate", models.CharField(max_length=45)),
                ("currency", models.CharField(max_length=45)),
                ("completion_rate", models.IntegerField()),
                ("disabled", models.BooleanField()),
                ("priority", models.IntegerField()),
                ("status", models.CharField(max_length=45)),
                ("reviewed_at", models.CharField(max_length=45)),
                ("rating", models.CharField(max_length=45)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfilePortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("description", models.TextField()),
                ("tags", models.TextField()),
                ("url", models.CharField(max_length=45)),
                ("files", models.TextField()),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to="job_seekers.jobprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("communication_rating", models.FloatField()),
                ("experience_rating", models.FloatField()),
                ("education_rating", models.FloatField()),
                ("skills_rating", models.FloatField()),
                ("comments", models.CharField(max_length=45)),
                ("status", models.CharField(max_length=45)),
                ("reject_reason_id", models.IntegerField()),
                ("next_review", models.DateField()),
                ("reviewed_by", models.IntegerField()),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="job_seekers.jobprofile",
                    ),
                ),
            ],
        ),
    ]
